version: '3.9'

services:
  app:
    build: .
    container_name: mojito-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mojitodb:5432/mojitodb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: mdp
    networks:
      - mojito-net

networks:
  mojito-net:
    external: true